using Microsoft.IdentityModel.Tokens;
using noteCodeAPI.Models;

namespace noteCodeAPI.Tools
{
    public static class DbInitializer
    {
        public static void Initialize(DataDbContext dbContext)
        {
            dbContext.Database.EnsureCreated();

            if (dbContext.Codetags.IsNullOrEmpty())
            {
                List<Codetag> codetags = new()
                {
                    new Codetag() { Name = "C#" },
                    new Codetag() { Name = "TypeScript" },
                    new Codetag() { Name = "Java" },
                    new Codetag() { Name = "C" },
                    new Codetag() { Name = "C++" },
                    new Codetag() { Name = "BASIC" },
                    new Codetag() { Name = "JavaScript" },
                    new Codetag() { Name = "ASP.NET" },
                    new Codetag() { Name = "ReactJS" },
                    new Codetag() { Name = "CSS" },
                    new Codetag() { Name = "Docker" },
                    new Codetag() { Name = "F#" },
                    new Codetag() { Name = "Dart" },
                    new Codetag() { Name = "Fortran" },
                    new Codetag() { Name = "Git" },
                    new Codetag() { Name = "Go" },
                    new Codetag() { Name = "HTML" },
                    new Codetag() { Name = "HTTP" },
                    new Codetag() { Name = "Ini" },
                    new Codetag() { Name = "JSON" },
                    new Codetag() { Name = "Kotlin" },
                    new Codetag() { Name = "LaTeX" },
                    new Codetag() { Name = "Lua" },
                    new Codetag() { Name = "Markdown" },
                    new Codetag() { Name = "MATLAB" },
                    new Codetag() { Name = "MongoDB" },
                    new Codetag() { Name = "nginx" },
                    new Codetag() { Name = "Ocaml" },
                    new Codetag() { Name = "Pascal" },
                    new Codetag() { Name = "PHP" },
                    new Codetag() { Name = "PL/SQL" },
                    new Codetag() { Name = "PowerShell" },
                    new Codetag() { Name = "Python" },
                    new Codetag() { Name = "Q#" },
                    new Codetag() { Name = "Razor C#" },
                    new Codetag() { Name = "ReactTS" },
                    new Codetag() { Name = "Regex" },
                    new Codetag() { Name = "Rust" },
                    new Codetag() { Name = "SCSS" },
                    new Codetag() { Name = "SQL" },
                    new Codetag() { Name = "VB.NET" },
                    new Codetag() { Name = "Visual Basic" },
                    new Codetag() { Name = "Web Assembly" },
                    new Codetag() { Name = "YAML" },
                    new Codetag() { Name = "ABAP" },
                    new Codetag() { Name = "Agda" },
                    new Codetag() { Name = "Arduino" },
                    new Codetag() { Name = "Assembly" },
                    new Codetag() { Name = "Bash" },
                    new Codetag() { Name = "BNF" },
                    new Codetag() { Name = "Clojure" },
                    new Codetag() { Name = "CoffeeScript" },
                    new Codetag() { Name = "Coq" },
                    new Codetag() { Name = "Dhall" },
                    new Codetag() { Name = "Diff" },
                    new Codetag() { Name = "EBNF" },
                    new Codetag() { Name = "Elixir" },
                    new Codetag() { Name = "Elm" },
                    new Codetag() { Name = "Erlang" },
                    new Codetag() { Name = "Flow" },
                    new Codetag() { Name = "Gherkin" },
                    new Codetag() { Name = "GLSL" },
                    new Codetag() { Name = "GraphQL" },
                    new Codetag() { Name = "Groovy" },
                    new Codetag() { Name = "Haskell" },
                    new Codetag() { Name = "Idris" },
                    new Codetag() { Name = "Julia" },
                    new Codetag() { Name = "Less" },
                    new Codetag() { Name = "Lisp" },
                    new Codetag() { Name = "LiveScript" },
                    new Codetag() { Name = "LLVM IR" },
                    new Codetag() { Name = "Makefile" },
                    new Codetag() { Name = "Markup" },
                    new Codetag() { Name = "Mermaid" },
                    new Codetag() { Name = "Nix" },
                    new Codetag() { Name = "Objective-C" },
                    new Codetag() { Name = "Perl" },
                    new Codetag() { Name = "Prolog" },
                    new Codetag() { Name = "Protobuf" },
                    new Codetag() { Name = "PureScript" },
                    new Codetag() { Name = "R" },
                    new Codetag() { Name = "Racket" },
                    new Codetag() { Name = "Reason" },
                    new Codetag() { Name = "Ruby" },
                    new Codetag() { Name = "Sass" },
                    new Codetag() { Name = "Scala" },
                    new Codetag() { Name = "Scheme" },
                    new Codetag() { Name = "Shell" },
                    new Codetag() { Name = "Swift" },
                    new Codetag() { Name = "TOML" },
                    new Codetag() { Name = "Verilog" },
                    new Codetag() { Name = "VHDL" },
                    new Codetag() { Name = "XML" },
                    new Codetag() { Name = "IDL" },
                    new Codetag() { Name = "Angular" },
                    new Codetag() { Name = "VueJS" },
                    new Codetag() { Name = "Visual Studio" },
                    new Codetag() { Name = "VS Code" },
                    new Codetag() { Name = "JetBrains" },
                    new Codetag() { Name = "VIM" },
                    new Codetag() { Name = "Flutter" },
                    new Codetag() { Name = "React Native" },
                    new Codetag() { Name = "Ionic" },
                    new Codetag() { Name = "Kubernetes" },
                    new Codetag() { Name = "Helm" },
                    new Codetag() { Name = "PowerApps" },
                    new Codetag() { Name = "PowerAutomate" },
                    new Codetag() { Name = "PowerBI" },
                    new Codetag() { Name = "PowerPlatform" },
                    new Codetag() { Name = "Dataverse" },
                    new Codetag() { Name = "MariaDB" },
                    new Codetag() { Name = "CosmosDB" },
                    new Codetag() { Name = "MySQL" },
                    new Codetag() { Name = "SQLite" },
                    new Codetag() { Name = "PostgreSQL" },
                    new Codetag() { Name = "Azure" },
                    new Codetag() { Name = "Google Cloud" },
                    new Codetag() { Name = "AWS" },
                    new Codetag() { Name = "SQL Server" },
                    new Codetag() { Name = "Oracle" },
                };
                dbContext.Codetags.AddRange(codetags);
                dbContext.SaveChanges();
            }
        }
    }
}
