name: Deployment dev

on:
  push:
    branches: [ "ci-cd" ]
    
env:
    IMAGE_NAME: notecode_api
    IMAGE_TAG: test-ci
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Debug secrets and variables
      run: |
          echo "REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}"
          echo "SERVER_HOST: ${{ secrets.SERVER_HOST }}"
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "DATE: ${{ env.CURRENT_DATE }}"
        
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        # Username used to log against the Docker registry
        username: ${{ vars.REGISTRY_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.REGISTRY_KEY }}
        
    - name: Docker meta data
      id: meta
      uses: docker/metadata-action@v5.6.1
      with:
        images: ${{ vars.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value={{commit_date 'YYYYMMDD-HHmmss' tz='Europe/Paris'}}
          type=raw,value=test-ci


    #- uses: actions/checkout@v4
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag notecode_api:$IMAGE_TAG
    #docker build --platform linux/amd64 -t mampao/notecode_webapp:v0.1 .
    - name: Docker build and push
      uses: docker/build-push-action@v6

      with:
        push: true
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        

    #- name: Deployment ssh
     # uses: appleboy/ssh-action@v1.2.0
      #with:
       # host: ${{ secrets.SERVER_HOST }}
        #username: ${{ secrets.SERVER_USERNAME }}
        #password: ${{ secrets.SERVER_PASSWORD }}
        #script: docker login -u ${{ vars.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_KEY }}
         #       docker pull ${{ vars.REGISTRY_USERNAME }}/$IMAGE_NAME:
                #docker run --name $IMAGE_NAME -p 2443:443 -e ASPNETCORE_URLS="https://+443;http://+80" -e ASPNETCORE_HTTPS_PORT=443 -e ASPNETCORE_Kestrel__Certificates__Default__Password=${{ secrets.CERTIFICATE_PASSWORD }} -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx -v ${{ vars.CERTIFICATE_DIRECTORY }} -d ${{ vars.REGISTRY_USERNAME }}/$IMAGE_NAME:test-ci

    

    #- name: Connecting to the server with ssh
     
