name: Deployment dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    environment: noteCodeAPI
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: notecode_api
      CURRENT_DATE: $(date %Y%m%d_%H:%M)
 

    steps:
    - name: Debug secrets and variables
      run: |
          echo "REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}"
          echo "SERVER_HOST: ${{ secrets.SERVER_HOST }}"
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "DATE: ${{ env.CURRENT_DATE }}"
      
          echo "Secrets fetched successfully"
        
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        # Username used to log against the Docker registry
        username: ${{ vars.REGISTRY_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.REGISTRY_KEY }}
        
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ vars.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value={{date 'YYYYMMDD-hh:mm' tz='Paris'}}
          type=raw,value=dev


    #- uses: actions/checkout@v4
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag notecode_api:$IMAGE_TAG
    #docker build --platform linux/amd64 -t mampao/notecode_webapp:v0.1 .
    - name: Build and push
      uses: docker/build-push-action@v6

      with:
        push: true
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}

    #- name: Connecting to the server with ssh
     # uses: appleboy/ssh-action@v1.2.0
      #with:
       # host: ${{ secrets.SERVER_HOST }}
        #username: ${{ secrets.SERVER_USERNAME }}
        #password: ${{ secrets.SERVER_PASSWORD }}
        #script: docker pull ${{ vars.REGISTRY_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
         #       docker run --name api-notecode -p 2443:443 -e ASPNETCORE_URLS="https://+443;http://+80" -e ASPNETCORE_HTTPS_PORT=443 -e ASPNETCORE_Kestrel__Certificates__Default__Password=${{ secrets.ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PASSWORD }} -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx -v ${{ secrets.ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PATH }} -d ${{ vars.REGISTRY_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
